### ISSUE TITLE
Bad Gateway - https://try.gitea.io/

### ISSUE THREAD

**Issue by ritiek** [go-gitea/website#58]
I stumbled across https://gitea.io/en-US/ but when I tap "Try Gitea", it responses with `Bad Gateway`.

**Comment by lafriks** [comment]
go-gitea/gitea#3147 fixes this, as soon as this is merged try gitea should be working again

**Comment by lafriks** [comment]
Fixed

**Comment by ritiek** [comment]
Thanks! I can confirm it works now.

**Comment by Adrian-Voelker** [comment]
Hello, 
the issue is back. 
When I open "https://try.gitea.io/", response is "Bad Gateway" again.

**Comment by hliebel** [comment]
Hi.
Broken for me too.
> Unable to connect
> Firefox can’t establish a connection to the server at try.gitea.io.
